FROM ubuntu:20.04

LABEL maintainer="amminer@pdx.edu"

# https://dev.to/grigorkh/fix-tzdata-hangs-during-docker-image-build-4o9m
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update -y
RUN apt install -y python3.9 python3-pip

COPY . /app

WORKDIR /app

RUN python3.9 -m pip install -r requirements.txt

ENTRYPOINT ["python3.9"]

CMD ["app.py"]
